---
application:
  name: "posternlch001"
  project: "posternlch"
  organization: "QoveryCommunity"
routers:
- name: "main-posternlch"
  routes:
  - application_name: "posternlch001"
    paths:
    - "/*"
